def content():
    return [
        "palmost done doinf meeting now",
        "Hi Patty, this is Jen with Desert First Cleaning. We wanted to check in and see if you still need a cleaning service. Our professional experienced crew is ready to clean your home and provide a satisfying result.\n\nIf you are still interested, please check the link below of your booking summary to check the pricing.\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/5f5afdc4d3d40241533e10a78564614d\n\nPlease don’t hesitate to contact us if you have any questions. Have a great day!",
        "I just want to know how was her cleaning. She updated me that shes done and spoke with you as well. ",
        "is doing invoices today? ",
        "We don't have a booking for you today Kayla. I'll let you know if I have a same day booking later.",
        "Yes, 2-3pm, or if you can go 1 thats great!",
        "Hi Kylee! please let me know your ETA to Pamela  Whittington today. thank you!",
        "Kylee, are you there now?",
        "It will be the middle of the night for me here",
        "I invoiced yesterday",
        "One moment let me check your last appointment ",
        "At any time",
        "Let me check with our crew of she is available. ",
        "he went to his father's house",
        "Hey Kylee, heres your booking for tomorrow 03/17. She'll be your regular customer for a weekly clean.\n\nFriday Clean\nETA 1-2 pm\n9033 E Gary Ln Mesa, AZ, 85027\n2bd | 2ba | 500 - 1000 sq/ft\nStandard clean\nPay 111.71\n\nCustomer job notes\nclean the exterior of cabinets\nClean the 1 bathroom from the room that no need to be clean",
        "Can you do a video call with her before and after the cleaning cos she can't meet you today\nWithney\n(858) 337-9531",
        "It's an emergency appointment. She will give you a tip afterwads if she is satisfied. 🎉",
        "Is this a regular clean, First appointment, or emergency appointment?",
        "The owner is not answering her FaceTime and I am on a very big time constraint so I'm trying to knock this out and I have no access to get into the unit",
        "Available for???",
        "The towels are in the dryer and the bedding for the half bedroom as well",
        "Kayla will be there at 11:50am",
        "\nwelcome anything else for the weekend",
        "Just the laundry and bedings only are not complete?",
        "I'm sorry I will have to leave. I can come back after my last appointment. I have pictures of all I have left the home and I will send them to you as soon as I arrive at my next appointment.",
        "Hello my phone wasn't working Amanda went this morning to Sheila's sorry for the inconvenience ",
        "Let me ask her what time she can comeback. ",
        "https://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/36d92c831393b4c81089880bc645bc5e",
        "I'm sorry but I need to put this on hold for now. My son won't be available on Sunday. Thank you for being so helpful and I will call you back when I have more information.",
        "whats the details",
        "is pamela knull a go for today? ",
        "Will do ... want a same day?",
        "i can after 4",
        "Yes we did!",
        "I'm good get some sleep",
        "I don't think she will close. She was complaining about the price.",
        "Can i get the same person as the first time",
        "Hey Kayla, are you interested in same-day booking? ",
        "Is this still the address? 925 South Gary Drive Tempe, AZ, 85281",
        "Feel free to accept the booking Mae if you want to go with us. Thank you so much!",
        "Hi Bobby, It's Jen, yes we have you on our calendar for Sunday 03/26, I'll update the time to 11am ETA",
        "I edited the booking. I put 3hrs, Kayla said she bring her helper. ",
        "Is this a small job",
        "Awesome! thank you Kylee. Here's your job for tomorrow. It's your bi-weekly customer.\n\nETA 9-10am\n120 N Kathy Dr,\nQueen Valley, AZ, 85118\n2bd | 1ba | 1001 - 1500 sq/ft\nStandard Cleaning\nPay $90.22",
        "Oh yah! 😅. Thanks Kylee",
        "for 400 sqft Studio, 2 hours is max.",
        "Our other crew is available tomorrow at 8:30 am. Let me know if you want to proceed now. I'll put you on our calendar today. \n\n6557 E Osborn Rd,\nAPT. 14\nScottsdale, AZ, 85251\nStandard Cleaning\n1 pet\nAmount: $ 166.40",
        "And ya thats perfect",
        "Hey Trevor, Kayla can do it around 2:30 pm. ",
        "I lost my 4198 card so its a new one",
        "Hi Kylee, good morning! just want to send you a reminder for your afternoon clean with Pamela Whittington 1-2pm ETA. Thank you!",
        "ok, Sounds good!",
        "Thank you! Im going to charge your card now. ",
        "No, if you could cancel that cleaning I would appreciate it. We're going to be moving so my house is in disarray with boxes, etc.",
        "No problem, Thank you for your response. Feel free to message us if you need our services in the future. Have a bless day!",
        "Hey Jazmine, are you interested for same day booking?",
        "I'm almost there",
        "I actually found a lower price for what I need, thank you anyway ",
        "Great! have you done walk through with the customer?",
        "Perfect! thank you Andrea please invoice $122.65 - #20230315-12264",
        "Okay thank you",
        "Hey Nicole, I'm waiting for my boss's response. I'll call you once I get an answer from him.",
        "Please invoice us $150.26-  #20230313-20100",
        "Link to photos sent. I also included pictures of the linen closet and what was available, which was no sheets for the other bed; however, I made the other bed up\nand much as possible. If need be, I can go back and finish after this cleaning. But if there was other linen and towels available I would've staged them and fixed the bed in its entirety for the next arrival.",
        "Thank you so much Kayla he is so happy! 🎉",
        "Great! Please do a videocall with Troy\n(219) 613-3256",
        "She did an amazing job! Thank you! ",
        "ptob gonna be close to 230 i have an airbnb first",
        "What time do you think is your ETA, so I can tell her",
        "Hello I'm available if you guys can send me more work that would be great ",
        "Hey Kayla. I have a job here for you for Modany!\n\nETA 1-2pm\n7219 S 12th Dr, Phoenix, AZ, 85041\nHourly Job $40/h\n- Bedroom, Vanity, and bathroom are cleaned. Just clean the 3 showers only kitchen, Countertop, and sink and mop the floors.\n-Pay $80 for 2 hrs job. We will add more if you finish it in more than 2 hrs",
        "Hey Marcus, just want to check on you how was the cleaning of Kayla?",
        "Sorry for all the drama",
        "What about Roland. Did you leave her alone in his shop?",
        "Sure, when do you need us?",
        "I'll inform Kylee, Thank you Pamela.",
        "Hey Troy, Kayla is done and she'll be calling you!",
        "I'll message you if they bite our price.",
        "Hey Kylee please update us when you are on your way to your afternoon clean. Thank you!",
        "one moment Renisha, please standby!",
        "i didnt get paid for yesterday",
        "walk through complete. for tomorrow it needs to be after 1pm",
        "It's because weekend, but I will follow up on that to Josh.",
        "Hey Marcus, fyi Kayla is almost there. 😊",
        "Hey Kayla Good morning! Josh is trying to send your payment but you didn't created a new Cashapp request. Please invoice us, and complete the job number.\n\nYesterday job - $120 - #20230319-95183\nToday - $80 - #20230314-54654",
        "Thank you and just know I could use your help tremendously..",
        "before pics",
        "is he gonna paye for sunday",
        "Good morning Andrea! please let me know when you are on your way to your morning clean today. thank you!",
        "Good morning Tashayanna! please update us when you are on your way to your morning job. Thank you!",
        "Sounds good ",
        "I'm heading to my appointment shortly ",
        "ehatd door vodr",
        "Ok perfect, thank you so much ",
        "Give it 2mins and it'll work ",
        "Did she get in ok?",
        "I'm finished",
        "Liked “Yes 😊”",
        "Please send me an invoice #",
        "Good morning, Pamela! Kylee will be there today between 1-2pm. Thank you!",
        "That's an hour away",
        "Thank you Tashayanna!",
        "Of course!! Thank you for the reminder ☺️ Happy Friday!!",
        "front door code 3010\nMaster bedroom at top of stairs - 9864.\n2nd upstairs bedroom- 5429\n Downstairs bedroom - 3021",
        "It'll be the same code ",
        "please wait for 2 mins then try the same code 3010",
        "They are good with it.",
        "Doing it now",
        "Hey Renisha are you available?",
        "Yeah! Happy Friday 🤩",
        "She can come back after 6pm I think cos her next job is a deep cleaning. And it takes 4 hrs. ",
        "whats the invoice and total for this one",
        "She was only here for 2.5 hours any way you can just bill me for that",
        "Done here after photos",
        "I did already 😊",
        "im done here  book for 3 hrs i had a helper too for ",
        "Just bill the new card i added",
        "Please invoice us $150.26 # 20230217-70814\n",
        "So am i only payjng for 2 hours online it says i am and she was here for 2 ",
        "https://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/2ffdf1885679932c418787e7bd5eb34d",
        "but can you do it alone?",
        "Hey Pamela, Just want to send you an update. Kylee is almost there! Thanks😊",
        "Please invoice us, Thank you!\n$111.71 - 03/17 -  #20230317-21868\n$111.71 - 03/21 - #20230314-54654",
        "there were 2 of us",
        "Let's do it",
        "Hey Kayla, just want to check on you. Are you there now?",
        "I believe it was some fraudulent felony charges from a couple years back ",
        "ok tomarrow is my birthday",
        "Do you have a time today 1-2pm",
        "ok thank you!",
        "Hi Tashayanna, the customer finally responded, and she wants you to come back and finish the job. Would you be able to do that? And what time you can do it, do you think?",
        "On my way now",
        "Can you please let the customer know So she can answer the phone when I video call her as I'm leaving.",
        "Hi Daniel, It's Jen with Desert First Cleaning. Feel free to accept the booking using the link below for us to put you on our calendar. \nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/c8e6942478188f454186f51b2b3b966d\n\nHere’s more information about the clean we quoted you:\nhttps://desertfirstcleaning.com/house-cleaning-services/\n\nPlease don’t hesitate to contact us if you have questions. Thank you and Have a great day!",
        "Ok, awesome. Thank you",
        "Hello, this is Desert First Cleaning. Sorry we missed your call. We are on the phone with another customer, and will call you back momentarily.\n\nIn the meantime, could you please send us the following information:\n* The type of clean you want\n* The number of bedrooms in your home\n* The number of bathrooms in your home\n* The square footage of your home\n\nIf you're not sure of the kind of clean you want, check out our cleaning checklists, which detail our services:\nhttps://desertfirstcleaning.com/cleaning-checklist/\nhttps://desertfirstcleaning.com/deep-clean-checklist/\n\nIf you'd like to book online, you can do so here:\nhttps://desertfirstcleaning.com/book-now/",
        "oh every pther day",
        "I believe we quoted you for an hourly job before minimum 2hrs. If you want to include the fridge, it depends on how many hours it takes to clean. If the cleaner finished it in 3hrs, we would charge you 210. Cos we charge 70/hour minimum of 2hrs, which is 140. ",
        "Ok will do thank you ❤",
        "Thats perfect",
        "Done here after photos",
        "No sent him the same after photos my phone is dying",
        "They are still not confirming!",
        "You sent her to a customer job Thursday knowing a client had accused her of stealing?",
        "Wow, YOU ROCK! have you met Pam?",
        "#20230323-86801",
        "Hey Kylee, Please invoice us $25 #20230314-75168 - 5-star Review",
        "I'm sorry she's not responding",
        "Hey Jazmine, Please invoice us $81.81 #20230217-43253",
        "I have been working at unable to respond I am sport ",
        "If she could go back and finish the job please! ",
        "he dodnt payme for yesterday am i gonna have to waot till monday now? ",
        "Unfortunately, we don't have available cleaner to finish the job before 4pm. all of them can do after 4pm. \n\nThe cleaner that I sent you earlier can go back to the property after her appointment so she can put bed sheet for the half room and the towels.",
        "Ok thank you",
        "Hi this is Pamela Whittington do you have a time when my maid will be coming today?",
        "Did you get it",
        "Yes I'm almost done",
        "anyword on pay",
        "Can we get a fridge cleanout",
        "Its only 45$ right",
        "Did you call him after you cleaned?",
        "Yes, I sent you the information to our customer portal. Please set up your new card there. ",
        "Ill add and extra half hour because she did a good job ",
        "Please invoice us $120 ($40/h x 3h) # 20230319-95183",
        "Hey Renisha, Good morning! are you available today for a move in cleaning? 11114 W College Dr, Phoenix, AZ 85037",
        "Hey Felix, Please accept the booking from the link below. If you want to add the exterior of the window we have additional of $5.50 per window. \n\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/ae5a36d5a42368238b50513a1994524c\n\nHere’s more information about the clean we quoted you:\nhttps://desertfirstcleaning.com/move-in-move-out-cleaning-service/\n\nFeel free to send us a message if you have any questions. Thank you and Have a great day!",
        "https://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/538f6cd0b3bbf3be281f7bf591ed4040",
        "Hey there- when would be the soonest someone could come by?",
        "If that time still works, let's do that",
        "Assist her at home when she is released.",
        "Good morning!",
        "https://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/50e66787d624fdb60397df3f868776d4",
        "Is the cleaner there ?? The guest is trying to check in ",
        "Liked “Please invoice us $101.14 - # 20230316-61669”",
        "Thank you so much! ",
        "Wait sorry Pamela is not your customer its for Kylee. My bad! I always switch your name",
        "Hi Patti, It's Jen with Desert First Cleaning. Feel free to accept the booking using the link below for us to put you on our calendar.\n\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/a3dca0e90994d66171bc51b898924690\n\nHere’s more information about the clean we quoted you:\nDeep Clean - https://desertfirstcleaning.com/deep-clean-service/\n\nFeel free to send us a message if you have any questions. Thank you and Have a great day!",
        "Hi Pamela, Yes, Kaylee will be there between 2-3 pm.",
        "Hi Trevor, It's Jen with Desert First Clean. I'm away at my desk and can't do a phone call now. May I know when do you need our service? ",
        "Are you good to go for your clean this afternoon?",
        "Same thing as the last two times",
        "Yes, cos we need to make sure that we received the payment first before we pay you guys.",
        "Done here after photos",
        "Kayla, he wants to add the fridge. So it's for the kitchen (including the inside of the refrigerator) and living area. Let me know how many hrs you will take so I can adjust the payment if you finish it in 3hrs. Thank you",
        "Thank you Renisha, I'll inform Troy ",
        "Hey Kayla, don't forget to update us, please. Thanks!",
        "Thank you, cos even its over 30minutes only we convert it into 1. \n\nSo we're going to use the **9055?",
        "Let me know when you can receive the info",
        "Hey Kayla, please update us when you are on your way to your afternoon clean. Thank you!",
        "Is it possible for you to tell me which of our jobs she went out on since you discovered she was stealing?",
        "Ok, I'll inform Josh. Thanks!",
        "whats invoice number",
        "heres the address 2202 N 11th St, Phoenix, AZ 85006",
        "Someone is supposed to check in so I'm not sure if it will work. ",
        "Please don't forget your schedule today with Pamela Whittington 1-2pm ETA. Thank you!",
        "All done with the last cleaning. Contacted the client and spoke to her as well",
        "Please invoice us $101.14 - # 20230316-61669\n\n",
        "I wanted to see if it was pretty slow for you guys or what's going on to see if I have to look for another contractor since it's been very slow ",
        "Let me know if you need anything ... will be up for another 15 minutes or so",
        "Hello, this is Desert First Cleaning. Sorry we missed your call. We are on the phone with another customer, and will call you back momentarily.\n\nIn the meantime, could you please send us the following information:\n* The type of clean you want\n* The number of bedrooms in your home\n* The number of bathrooms in your home\n* The square footage of your home\n\nIf you're not sure of the kind of clean you want, check out our cleaning checklists, which detail our services:\nhttps://desertfirstcleaning.com/cleaning-checklist/\nhttps://desertfirstcleaning.com/deep-clean-checklist/\n\nIf you'd like to book online, you can do so here:\nhttps://desertfirstcleaning.com/book-now/",
        "Hi Pamela, good morning! I want to confirm your appointment every Monday and Friday for cleaning with Kylee. Thank you!",
        "Help with cleaning a small kitchen/ living room area",
        "I added my card thank you",
        "I'm so sorry to hear that. I know you are strong, and you will overcome everything. I pray for your quick recovery.",
        "See you tomorrow! Kayla will be the cleaner 😊 Thank you!",
        "We definitely want to be prepared for the conversation when she does.",
        "And this just occurred on Friday",
        "Hi Nicola, good morning! Just want to confirm your appointment tomorrow for a monthly house cleaning. Thank you!",
        "For sure, thanks for letting us know.",
        "I gave her mostly my jobs with my customers I didn't give her the work u gave me other than Sheila's and I checked with all the clients she does or had done since this occurs and everyone is saying they aren't missing anything ",
        "No I found out Friday she was stealing because Friday was the day she went to the home to do the cleaning and then when she left is when I git a call from her if your saying Thursday as last week she told me she couldn't go because she was sick ",
        "She did a very good job 👏 thanks you ",
        "Hey Kayla any update on you?",
        "done u cnam call him now",
        "Hi Whitney, I'm out of my desk now! Have you spoken with Tashayanna?",
        "lmk qbout yesterdays payment please",
        "Ok, we will let you know ",
        "Are you still using this email address? kojispiv@gmail.com, I'll invite you to our customer portal so you can add your new card details there. ",
        "Im doing it online",
        "Btw, I have two cards here on your account (**9055 and **4198). May I know which one we are going to use? ",
        "Hey Troy, Renisha is done cleaning today. ",
        "what the invoice number and total",
        "Ok thats fine",
        "Good morning Kayla! job reminder for today. Thank you!\n\nETA 1-2pm\n7219 S 12th Dr, Phoenix, AZ, 85041\nHourly Job $40/h\n- Bedroom, Vanity, and bathroom are cleaned. Just clean the 3 showers only kitchen, Countertop, and sink and mop the floors.\n-Pay $80 for 2 hrs job. We will add more if you finish it in more than 2 hrs",
        "https://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/ae5a36d5a42368238b50513a1994524c",
        "Hey Renisha, any update from Gary? because the customer want it to be done today he has a client who wants to check to property.",
        "Gary is busy today ",
        "Awesome! thank you!",
        "I'm not sure if you guys are in contact with Amanda but she has stolen some things from some of my clients homes that I have and I have not paid her since finding these things out I had to compensate for gold necklaces and valuable things with the pay that she would've gotten for working but since I had complaints about her stealing she is no longer working with me and is saying she will be getting in contact with you guys for you guys to pay her out since I didn't pay her just and fyi ",
        "Hi Pamela, Kylee informed us that she is done. Your next appointment with us in on  Friday 03/24. Thank you!",
        "I'm already here",
        "Has she contacted you guys? ",
        "Thank you Kylee! I'll let you know if we have a booking for you tomorrow!",
        "Let me know if you can 8-8:30 am on Sunday.",
        "Btw Kayla on Monday 03/27, I booked you for that job again.",
        "try to get wm to tip it was messy",
        "What time in the morning?",
        "be there at 1pm",
        "Hi Pam! Kylee will be there between 9-10am tomorrow 😊",
        "Please invoice us!\nYesterday job - $120 - #20230319-95183\nToday - $80 - #20230314-54654",
        "Yes we do I just wanted to let you guys know because she said she was going to contact you guys regarding pay which I had already told her she will not be getting since I had to compensate for the things she stole so she got a hold of a couple customers she did jobs for that were mine but I also let them know so just wanted to give you guys a heads up since she said she was going to be calling you guys, I wasn't aware that she was also a felon my attorney just found that out. Do not sure what the communication was with you guys but just wanted to let you guys know.",
        "Hi Pam, Kylee inform us that she's done. Just want to check on you before we charge your card. How was her cleaning today?",
        "No I did that with her. ",
        "Very impressive! ",
        "Hey Renisha, are you available tomorrow for a cleaning? \n6557 E Osborn Rd, APT. 14",
        "For today? That is for a standard clean only",
        "Ok one moment, if no one is available tomorrow, I'll book it for Sunday",
        "I'll get back to you if he confirms today.",
        "ETA 8:30am\n6557 E Osborn Rd, APT. 14\nScottsdale, AZ, 85251\nStandard Cleaning\nStudio home with 400sqft\nPay: $ 91.52",
        "Hey Jazmine, this is John! I'm sorry to hear you're having trouble with her. These are pretty serious allegations. Do you or your customers have any proof of them?",
        "My customer had a small camera in her room where it had view to her jewelry box and had clear view of her grabbing a couple things from there. ",
        "When did this theft occur?",
        "You didn't communicate that to us?",
        "the  boys i did 2 days ago were return customers too",
        "Thank you so much, Pam! your next appointment is on April 4.",
        "When will she be returning?",
        "i need u to call client my tire on my car is flat",
        "Hello John\nAnything available for this Sunday at 11am checkout for a 4pm check in? They probably will leave at 10am or 10.30. \nI know we talked about it a while ago but if you do not for this Sunday, I understand. ",
        "I lon my way in 10 min",
        "Hello, this is Desert First Cleaning. Sorry we missed your call. We are on the phone with another customer, and will call you back momentarily.\n\nIn the meantime, could you please send us the following information:\n* The type of clean you want\n* The number of bedrooms in your home\n* The number of bathrooms in your home\n* The square footage of your home\n\nIf you're not sure of the kind of clean you want, check out our cleaning checklists, which detail our services:\nhttps://desertfirstcleaning.com/cleaning-checklist/\nhttps://desertfirstcleaning.com/deep-clean-checklist/\n\nIf you'd like to book online, you can do so here:\nhttps://desertfirstcleaning.com/book-now/",
        "Hi Felix, this is Jen with Desert First Cleaning. We wanted to check in and see if you still need a cleaning service. Our professional experienced crew is ready to clean your home and provide a satisfying result.\n\nIf you are still interested, please check the link below of your booking summary to check the pricing.\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/ae5a36d5a42368238b50513a1994524c\n\nHere’s more information about the clean we quoted you:\nhttps://desertfirstcleaning.com/move-in-move-out-cleaning-service/\n\nPlease don’t hesitate to contact us if you have any questions. Have a great day!",
        "Hey, Kayla are you available tomorrow morning? 6557 E Osborn Rd, APT. 14",
        "I'll have to double check on that time",
        "Let me ask the cleaner that we sent out last time if she can do it at 9am. Or maybe you have a preferred time?",
        "I'm waiting for the response of my other cleaner if she can do 8am tomorrow. But Renisha is available on Sunday morning.",
        "If they came at 9 tomorrow- what time do you think they would be finished?",
        "Hi Bobbi, Good morning! It's Jen with desert first cleaning. I spoke with my boss and he is agree for visiting your house first so you can tell our cleaner what they need to do. Just want to confirm your address and when you are available? 18242 N 170th Ln, Surprise, AZ 85374, United States",
        "Let me get back to you",
        "Get well soon!",
        "hmmm, is that about what John told you last time?",
        "Tuesday she was actually sick and canceled on me last min not because of anything else ",
        "Any jobs in the near future?",
        "Hey Caleb, How things were going? How was your wife now and your new baby?",
        "Hey john, funny you ask, we actually have a huge 40 person event going on at cave creek property right now which will be ending on March 30th. I'll let you know if we end up needing a deep clean based on how the event goes. ",
        "Good Morning! this is Jen with Desert First Cleaning. Our crew is now on her way ETA is 10:40 am.  Thank you!",
        "Good morning Kayla! please message me if you have any questions for Troy AirBnB. Thank you!",
        "Hi Suzanna, I have now Tashayanna for you and she will be there after her morning cleaning. ETA between 12:30-1:30pm. Thank you!",
        "Pamela, Just want to let you know that we charged your card for the job last Friday and for today's job. We have yet to charge it last week, because we experienced some technical issues. Thank you!",
        "Ok hopefully she doesn't get in contact but if she does she may just ask you guys for pay for Sheila's home just wanted to give u guys a heads up so u guys aren't caught by surprise. ",
        "Good morning Kylee, please update us when you are on your way to 120 N Kathy Dr, Queen Valley, AZ, 85118. Thank you!",
        "If you booked with us for a biweekly cleaning I will give you 15% off and for every 3weeks 12%off.",
        "Ok thank you ",
        "Hey Bradley, we have available tomorrow morning and afternoon clean 😊 What time do you prefer?",
        "I have only sent her out to Sheila's I believe that's the last one all of the other ones I did myself ",
        "Renisha will be there between 9-10 am . Thank you!",
        "i sent rhe request 2 days ago",
        "still waiting for payment",
        "Heading to client's home eta 10:40",
        "Also, how long will the cleaning take?",
        "Hey Kayla, I assign you for Howingtons scheduled for Thursday, 03/30. She's your regular customer before, but we assigned her to another crew during the time that you are not responding to us. But that crew now is no longer working with us. \n\nETA 8:00am-9:00\n8010 S 34th Place Phoenix, AZ, 85042\nStandard cleaning\n1 bed/ 2 and a half bathroom, kitchen, dining, and living area. \nPay $81.81\n\nThe customer will provide cleaning products. Please don’t use water on old laminate flooring. Use her cleaning supplies.\nNote: turn left on 36th, gate code #9217",
        "please and thankyou",
        "Hi Autumn, thanks for your call. Please accept the booking from the link below for us to put you on our calendar.\n\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/20344bf5fd870ea01a143cb491747eb0\n\nHere’s more information about the clean we quoted you:\nhttps://desertfirstcleaning.com/deep-clean-service/\n\nFeel free to send us a message if you have any questions. Thank you and Have a great day!",
        "I have a Thursday regular ",
        "We're glad to know that you are satisfied with the outcome. I hope you have some time today, and we would appreciate it if you could give us a review.\n\nWe are a small business, and much of our success depends on online reviews. If you could leave us a 5-star review on Google, it would really help us.\nhttps://g.page/r/CfI7zpAl6UkbEB0/review",
        "For yesterday's job? I'll follow up on that with Josh. Usually, he sends it the next day after the cleaning cos we need to ensure that we received the payment from the customer after we charged their card. Did you include the last 5digits of the job number to your request?",
        "done walk thru weng well",
        "What time will you have the housekeeper here tomorrow 3/21?\nThanks ",
        "Thank you so much, Marcus! We're glad to know that you are satisfied with the outcome. I hope you have some time today, and we would appreciate it if you could give us a review.\n\nWe are a small business, and much of our success depends on online reviews. If you could leave us a 5-star review on Google, it would really help us.\nhttps://g.page/r/CfI7zpAl6UkbEB0/review",
        "you did it in 1 and half hrs?",
        "whats invoice number",
        "#20230323-45187 \n$150.26",
        "Hey Andrea, I'll get back to you once I've got a response from John.",
        "She went to Sheila's on Thursday the stealing occurred on Friday and I git the proof yesterday as to why she has been contacting everyone to try to get paid on her own instead of me taking the amount she was to be paid and compensate the customer ",
        "At what time",
        "He will pay it in the morning!",
        "Please can you text my husband any details as he will be the one at home when you come. His cell is 650 450 2035. Thank you. ",
        "Andrea will be there between 10-11am. ",
        "Let me ask, if she can. and the cleaning will take 3-4hours depending on the sqft and situation of the house.\n\nHere’s more information about the clean we quoted you:\nhttps://desertfirstcleaning.com/move-in-move-out-cleaning-service/",
        "Please invoice us \nPay $104 - #20230201-68226",
        "Am I able to add tip through you?",
        "What day am I coming back to todays location. 3rd or 4th? And what will be the pay for that cleaning?",
        "annie is done",
        "Hey Kylee, are you available on Thursday morning for a cleaning?\n8010 S 34th Place Phoenix, AZ, 85042",
        "She is one of our recurring customers, but the cleaner that we assigned to her is no longer working with us. \n\nThursday 03/30\nETA 8:00am-9:00\n8010 S 34th Place Phoenix, AZ, 85042\nStandard cleaning\n1 bed/ 2 and a half bathroom, kitchen, dining, and living area.\nPay $81.81\n\nThe customer will provide cleaning products. Please don’t use water on old laminate flooring. Use her cleaning supplies.\nNote: turn left on 36th, gate code #9217",
        "Gotcha! Thanks!",
        "Hi Mary, It's Jen with Desert First Cleaning. We double-checked our system here and we didn't get your card details yet. For us to put you on our calendar, please click the link below and hit the ACCEPT/BOOK and put your card details.\n\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/e0bfc531c14fb2a4c5add5096aafd877\n\nHere’s more information about the clean we quoted you: \nhttps://desertfirstcleaning.com/deep-clean-service/\n\nFeel free to send us a message if you have any questions. Thank you and Have a great day!",
        "Hey Kylee, job for you this Sunday 03/26\n\nHourly Job - 3 hours ($40/h)\n736 East Rojo Way, 101 Gilbert, 85297\nVRBO- 3 bed 3 bath Laundry put new sheets and pillow\nPay $120",
        "I am not available tomorrow but I am Sunday",
        "Yes I can get there at 830",
        "He wants it for tomorrow morning 😔 I'll try with other cleaners. Thank you!",
        "Unfortunately my Cancer really got worse yesterday and I would love the help but won't be able to do it for that much right now. Thank you",
        "Interesting. Do you know what felony charges have been brought against her?",
        "I checked with a lot of my other customers and they said they aren't missing anything so I think she's going through financial problems at the moment and just decided to take the chances because she has cleaned this customers home and nothing has gone missing until now. I'm just starting out my business and getting the hang of it so I have a lot to learn.",
        "Yes, thank you,  what time are you arriving?",
        "that was a diffrent customer",
        "Excellent as usual!",
        "Please wait cos sometimes Cashapp has delay",
        "Hello, this is Desert First Cleaning. Sorry we missed your call. We are on the phone with another customer, and will call you back momentarily.\n\nIn the meantime, could you please send us the following information:\n* The type of clean you want\n* The number of bedrooms in your home\n* The number of bathrooms in your home\n* The square footage of your home\n\nIf you're not sure of the kind of clean you want, check out our cleaning checklists, which detail our services:\nhttps://desertfirstcleaning.com/cleaning-checklist/\nhttps://desertfirstcleaning.com/deep-clean-checklist/\n\nIf you'd like to book online, you can do so here:\nhttps://desertfirstcleaning.com/book-now/",
        "Ok I'll let her know",
        "Hi, I was checking maidly for this week schedule and came across this for 3/30. Is this a for sure customer?",
        "Cindy will be your cleaner Steve and her ETA is between 7:30-8:30. \n\nFor the carpet cleaning .40/sqft. How many sqft is your carpet do you think?",
        "Approximately 500SF",
        "For how much, what kind of cleaning and how big? ",
        "Yeah, its for a standard cleaning only with baseboards \nPay - $127.39",
        "Hey Kayla! FYI The SOP states:  We pay cleaners 55% of the full price of a job.  Payouts are completed in the mornings, approximately every other day, using Cash App.  Given the time it takes to confirm a clean is satisfactory and initiate a charge to a customer, cleaners should expect a wait of 48-72 hours for Cash App payments to be paid.  Additionally, if the job number is missing or inaccurate on a Cash App request, it will delay the payout by a minimum of 24 hours.\n\nAnd Josh tried to paid you this morning but the job number you've sent was incomplete.\n\nPlease check our SOP from this link:\nhttps://docs.google.com/document/d/1nAEAX88ENbdalZ01QubZ1bDY9KYRwMByddFOeDEBCW8/edit?usp=sharing",
        "Yes, this is my second time here I did the deep clean",
        "No, I mean I've already met her before because I did the deep clean for her two weeks ago",
        "Hi Leilani, this is Jen with Desert First Cleaning. We wanted to check in and see if you still need a cleaning service. Our professional experienced crew is ready to clean your home and provide a satisfying result.\n\nIf you are still interested, please check the link below of your booking summary to check the pricing.\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/538f6cd0b3bbf3be281f7bf591ed4040\n\nHere’s more information about the clean we quoted you:\nhttps://desertfirstcleaning.com/move-in-move-out-cleaning-service/\n\nPlease don’t hesitate to contact us if you have any questions. Have a great day!",
        "I wonder if I should be checking with my customers to see if they are missing anything.",
        "Hi Renisha, I'm sending you a reminder about your job for tomorrow. Thank you!\n\nMonthly Cleaning\n15902 e Jericho Drive fountain hills, AZ, 85268\n4bd | 3ba | 1501 - 2000\nStandard Cleaning only \nPay $120",
        "Great! thank you. Please invoice us \n$154.82\n#20230310-91614",
        "$120 - #20230319-95183",
        "Awesome, keep us posted. We'd love to help you out!",
        "Hi Kiah, how are you doing? Just want to check on you and see if there are any projects we could bid on.",
        "Is the VRBO for today a same day?",
        "Hello, this is Desert First Cleaning. Sorry we missed your call. We are on the phone with another customer, and will call you back momentarily.\n\nIn the meantime, could you please send us the following information:\n* The type of clean you want\n* The number of bedrooms in your home\n* The number of bathrooms in your home\n* The square footage of your home\n\nIf you're not sure of the kind of clean you want, check out our cleaning checklists, which detail our services:\nhttps://desertfirstcleaning.com/cleaning-checklist/\nhttps://desertfirstcleaning.com/deep-clean-checklist/\n\nIf you'd like to book online, you can do so here:\nhttps://desertfirstcleaning.com/book-now/",
        "Good morning Alia! Cindy will be your cleaner today, and she will be there between 1-2pm 😊. Thank you!",
        "Great. Thank you!",
        "Would you rather we assign them to someone else?",
        "All done! ☺️",
        "Hey Suzanna, Tashayanna updated me that she's done. Just want to check on you. how was her cleaning today?",
        "Good morning! I'll check with the customer one moment 😊",
        "Hello, this is Desert First Cleaning. Sorry we missed your call. We are on the phone with another customer, and will call you back momentarily.\n\nIn the meantime, could you please send us the following information:\n* The type of clean you want\n* The number of bedrooms in your home\n* The number of bathrooms in your home\n* The square footage of your home\n\nIf you're not sure of the kind of clean you want, check out our cleaning checklists, which detail our services:\nhttps://desertfirstcleaning.com/cleaning-checklist/\nhttps://desertfirstcleaning.com/deep-clean-checklist/\n\nIf you'd like to book online, you can do so here:\nhttps://desertfirstcleaning.com/book-now/",
        "I'll book you for Sunday 8:30 am ETA with Renisha. Just want to confirm your address is still the same and for a standard cleaning?\n\n6557 E Osborn Rd,\nAPT. 14\nScottsdale, AZ, 85251",
        "Where is this address located It sounds familiar also what are the other details is this a small place ",
        "Returned customer bonus 03/15/2023 20230306-18540 $25.00",
        "Yes I didn't want to let you guys know until I for sure had the evidence in hand ",
        "Rebook bonus #20230319-95183 $25",
        "Hi Nick, how are you doing? Just want to check on you and see if you have any deep cleans coming up?",
        "Hello, this is Desert First Cleaning. Sorry we missed your call. We are on the phone with another customer, and will call you back momentarily.\n\nIn the meantime, could you please send us the following information:\n* The type of clean you want\n* The number of bedrooms in your home\n* The number of bathrooms in your home\n* The square footage of your home\n\nIf you're not sure of the kind of clean you want, check out our cleaning checklists, which detail our services:\nhttps://desertfirstcleaning.com/cleaning-checklist/\nhttps://desertfirstcleaning.com/deep-clean-checklist/\n\nIf you'd like to book online, you can do so here:\nhttps://desertfirstcleaning.com/book-now/",
        "Hey Kylee, please invoice when you are done. Thank you!\n$111.71\n#20230320-28836",
        "I am currently at my second job. I will send a request when I'm off:)",
        "Good morning Steve! thank you for booking with us. I'll get back to you on Saturday with the name of your cleaner. Thanks again and have a bless day!",
        "Good morning Cindy! I hve another booking for you for Saturday 04/01\n\nJob for SATURDAY:\nETA 7:30-8:30 AM\n431 S Marina St\nPrescott, AZ, 86303\n2bd | 1ba | 1001 - 1500 sq/ft\nMove in cleaning\nhttps://desertfirstcleaning.com/move-in-move-out-cleaning-service/\nPay $169.12\n\n- Please let confirm you accept the job. Thank you!",
        "perfect! hope he will add, lol 💰 Thank you Cindy!",
        "Hi Andrea, please invoice us for your job earlier, that is for a standard cleaning only. \n$101.92\n#20230310-91614",
        "Hi Kayla, what time do you think you can get there?",
        "arrived at annies",
        "thats the lady idont likeher cleaning supplirs are not goos",
        "It went well, thank you!",
        "Good morning Kylee! sorry I sent you the incorrect Job number for 03/21 - here's the correct job #20230307-79068 - Pay -$90.22",
        "I find cheaper another one.Thank you for your feedback ",
        "Hey John so not sure since the conversation we had earlier if u no longer would like to give me work let me know that way I can contact other contractors to get more work since I do need work at the moment thank you.",
        "Thank you for letting us know. Feel free to message us if you need us in the future.",
        "Good morning, Renisha! please update us on your ETA for your job this morning. Thank you!",
        "Hey Andrea! I just want to remind you about your biweekly clean. Thank you! \n\nTom and Sherry Baran\n1862 South Skyview Place\nTucson, AZ, 85748\n(520) 271-4380\n\nETA 10AM\n3bd | 2ba | 1001 - 1500 sq/ft\nStandard clean\n$154.82",
        "Thank you! and please don't forget your todays clean at 1-2pm 😊",
        "Liked “Great! we will call today your customer for Thursday, that we will assign you to them 😊”",
        "Great! thank you 😊",
        "Yes, I can handle that.",
        "For Suzanna, I scheduled her on Monday 04/03 same cleaning with baseboards 😊",
        "Yes, but you can also give it directly to Cindy. 😊",
        "Sorry I booked a cleaning for Thursday as I was waiting to here back from you yesterday. I thought hourly jobs were 40 an hour?",
        "I don't remember you disliking them specifically.",
        "Hi Mae, this is Jen with Desert First Cleaning. We wanted to check in and see if you still need a cleaning service. Our professional experienced crew is ready to clean your home and provide a satisfying result.\n\nIf you are still interested, please check the link below of your booking summary to check the pricing.\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/2ffdf1885679932c418787e7bd5eb34d\n\nHere’s more information about the clean we quoted you:\nhttps://desertfirstcleaning.com/house-cleaning-services/\n\nPlease don’t hesitate to contact us if you have any questions. Have a great day!",
        "Does this have anything to do with why you told us she was unavailable for jobs last week? That thing on Thursday with the Howingtons was super weird.",
        "What proof do you have that she stole from your customers?",
        "Can you explain again why you told us she was out sick Tuesday? I don't think I understand.",
        "I know, but the job number you sent is incomplete",
        "I don't think it makes sense for us to continue working with you. ",
        "Cool 03/22 🎉 Happy Birth Day Kayla! it's 22 here already in the Philippines lol😁",
        "I believe josh sent it already",
        "Let me check with the cleaner what time do you prefer if ever?",
        "How much is the carpet cleaning service? Is that something that can be added on Saturday or do I need to schedule prior?",
        "I'll be heading that way in about 15 min with an travel time of 35min",
        "Hey Renisha, here are the details for your job on Thursday. \n\nETA 8:00am-9:00\n8010 S 34th Place Phoenix, AZ, 85042\nStandard cleaning\n\nit's an hourly job with 1 bed/ 2 and a half bathroom, kitchen, dining, and living area. It’s a 2.5-hour job. pay will be 81.81 (32.72 hourly)\n\nThe customer will provide cleaning products. Please don’t use water on old laminate flooring. Use her cleaning supplies.\nNote: turn left on 36th, gate code #9217",
        "She has an appointment at 1pm, but she said if could be there at 2:30 today cos she wants to be there while you are cleaning",
        "Perfect! thank you!",
        "Perfect! thank you",
        "Thank you very much!",
        "we will add extra for that Steve will think of it on Saturday if he will add the carpet once he measured it.",
        "Thank you! if you could, please send us before and after pics, so that we can upload them on our page. Thank you!",
        "Great! we will call today your customer for Thursday, that we will assign you to them 😊",
        "Hey Kylee, I received a message from Pamela. \n--\nI won't be home today until 1pm today I'm at rehab with my mom she was transported there and I'm learning P/T for when d so he comes home I know how to ss",
        "Hi Harry, please click the link below and ACCEPT/BOOK for us to put you on our calendar. Thank you!\n\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/a864a8aa2144e84ab64c1d8b1102d3b0\n\nHere’s more information about the clean we quoted you:\nhttps://desertfirstcleaning.com/move-in-move-out-cleaning-service/\n\nTerms of service:\nhttps://desertfirstcleaning.com/terms-of-service/\n\nFeel free to send us a message if you have any questions. Thank you and Have a great day!",
        "Hello, this is Desert First Cleaning. Sorry we missed your call. We are on the phone with another customer, and will call you back momentarily.\n\nIn the meantime, could you please send us the following information:\n* The type of clean you want\n* The number of bedrooms in your home\n* The number of bathrooms in your home\n* The square footage of your home\n\nIf you're not sure of the kind of clean you want, check out our cleaning checklists, which detail our services:\nhttps://desertfirstcleaning.com/cleaning-checklist/\nhttps://desertfirstcleaning.com/deep-clean-checklist/\n\nIf you'd like to book online, you can do so here:\nhttps://desertfirstcleaning.com/book-now/",
        "Ok thank you! Is 9AM the earliest they can do it?",
        "Kayla will be there at 2:30pm 😊",
        "I have arrived and completed walkthrough with client",
        "Good morning Suzanna! Tashayanna again will be your cleaner today and her ETA is between 9:30-10:30 am. Thank you!",
        "Pay request sent! ☺️",
        "Let me ask John, but I believe because they are one of our regular customers",
        "I'm here unloading my car and. Meeting the customer  now",
        "Hey Cindy, another job for you for next week, Tuesday 04/04.\n\nETA 9-10 am \n1230 Northwood Loop\nPrescott, AZ, 86303\n3bd | 3ba | 4001 - 4500 sq/ft\n2 extra room \nMove in clean\nhttps://desertfirstcleaning.com/move-in-move-out-cleaning-service/\nPay $413.87\n\n- If you have assistance to help you that would be great!",
        "Ok, what is the pay for  The cleaning on 4/3 since it is a one time with baseboards?",
        "Sorry I'm not use to nails ",
        "I can measure on Saturday if needed for an exact ",
        "Sounds good! just let me know. 😊",
        "All good, I moved it to Tuesday, April 4th. 9-10am ETA 😊",
        "whats invoice anf total",
        "I have not received a cash app deposit",
        "Awesome! btw, are you available on Thursday?\n\nThursday 03/30\nETA 8:00am-9:00\n8010 S 34th Place Phoenix, AZ, 85042\nStandard cleaning\n1 bed/ 2 and a half bathroom, kitchen, dining, and living area.\nPay $81.81\n\nThe customer will provide cleaning products. Please don’t use water on old laminate flooring. Use her cleaning supplies.\nNote: turn left on 36th, gate code #9217",
        "Also does 169 include the carpet cleaning or  will  I get paid extra for that ",
        "Hi Treva, this is John Davenport. I'm folllowing up on your message from care.com",
        "Hi Drew, it's Jen with Desert First Cleaning. Just want to check on you to see if you are still looking for a cleaning service.",
        "#20230201-62872 - $94.43",
        "That's awesome ",
        "Thank you for letting us know. 😊",
        "Omw to client. ETA 8:35",
        " Yes she was happy I just need the  reference code",
        "walkthru complete",
        "Thank you!\n#20230201-62872 - $94.43",
        "#20230201-62872 - $94.43",
        "Thank you Cindy! did she give you a tip? cos she asks me she could add a tip through me. But I told her that she can give it to you directly.",
        "Good afternoon. I wanted to know if we can switch my appointment from the 3rd to the 4th. I forgot that I have an important meeting that day that I was just reminded of. ",
        "Grand Rising! ☺️",
        "Ok I'll try to call her, have you done a walk-through with Alia?",
        "Hi there, this is Jen with Desert First Cleaning. We wanted to check in and see if you still need a cleaning service. Our professional, experienced crew is ready to clean your home and provide a satisfying result.\n\nIf you are still interested, please check the link below of your booking summary to check the pricing.\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/20344bf5fd870ea01a143cb491747eb0\n\nPlease don’t hesitate to contact us if you have any questions. Have a great day!",
        "Great! Thanks!",
        "Good morning!",
        "ok! I'll update",
        "Hi Steve, Good morning! Just want to check if you would like to add the carpet?",
        "No problem! thank you, Steve.",
        "Hey Bobby, just want to check on you. how was the cleaning of Kayla?",
        "Sure!\n#20230217-75050 - $93.48\n##20230316-61397 - $111.71",
        "Are you available today for a standard cleaning? 27721 N 220th Dr,\nWittmann, AZ 85361",
        "Working on it",
        "Please take the before and after pictures, we need to send that to the customer.",
        "Heading to my next appointment ",
        "Shoot! I didn't check ",
        "whats he complaining about",
        "When you get a chance can you send me the reference  numbers",
        "yes i talked with him",
        "checking in pn todays clean",
        "No worries, I'll look for a new company. You all charge for cleaning inside the refrigerator. I have companies that I use that that is standard cleaning. ",
        "Hi Linda, it's Jen with Desert First Cleaning. We wanted to check in and see if you still need a cleaning service. Our professional, experienced crew is ready to clean your home and provide a satisfying result.\n\nPlease don’t hesitate to contact us if you have any questions. Have a great day!",
        "Hello,\n\nI can't seem to get into the portal . I requested to change the password , but the portal seems to be slow . ",
        "#20230322-51774 - Pay $170.77",
        "Thank you! have you walk-though with Sheila?",
        "https://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/1f8139ab17e2983f4d271f35643ec1c0",
        "Good morning Pamela! Kylee will be there between 1-2pm today. Thank you!",
        "Good morning Bobby! Let me check with my other crew.",
        "Kayla be there at 11am, cos there's a same-day check-in",
        "Sorry about that, here's the docs for our SOP. \nhttps://docs.google.com/document/d/1nAEAX88ENbdalZ01QubZ1bDY9KYRwMByddFOeDEBCW8/edit",
        "I'll pass that on to Kayla. Thank you, Bobby!",
        "Garage code is\n1982 Enter",
        "Your Indeed verification code is: 442079",
        "As soon as possible!! Check in is at 4pm",
        "whats janice invoice number and total",
        "Are you available for the same day cleaning? its a VRBO for 3 hours job",
        "Hey Kylee, my bad for Bobby Delocas I sent you incorrect amount of payment. Because he is a recurring customer and we gave them a discount. And he needs a clear today. I'll try with Kayla for now. \n\n3 hours Job - $93.48\n736 East Rojo Way, 101 Gilbert, 85297\nVRBO- 3 bed 3 bath Laundry put new sheets and pillow",
        "I understand. To my understanding, I was made the bi-weekly cleaner after this client was already scheduled one. With this information, I definitely felt it was safe to assume that the cleaning was more than satisfactory. Also I have yet to receive any handbook with Desert Cleanings Polices and procedures so I was unaware of this information. Have a great day.",
        "Do you have the before and after picture?",
        "For troy, the Airbnb you've clean on the 27th",
        "Hi Pam, Good morning! Sorry for the late response, I'm going to cancel your biweekly subscription now and change it to a monthly visit. See you on April 18. Thank you so much and have a great day!",
        "No problem thank you!",
        "How much is the service ",
        "Hi Hannah, It's Jen with Desert First Cleaning. We have an availabe crew this afternoon. Could you please send me your complete address. Thank you!",
        "Do you know maids ATA",
        "Invoice us Kayla, $138.36 - #20230306-07188",
        "All good for Suzanna 😊",
        "I confirmed with my brother in law that the cleaning is set for April 4 @ 9:00 am to 10",
        "Awesome thank you ",
        "Hi Jayson, It's Jen with Desert First Cleaning. Feel free to accept the booking using the link below for us to put you on our calendar. Thank you!\n\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/103f638442972c1c86c9fa538b868d4f\n\nFor a Biweekly cleaning we will give you a 15% off, so for Standard clean instead of $318.00 we discounted it to $ 270.30.\n\nHere’s more information about the clean we quoted you:\nhttps://desertfirstcleaning.com/deep-clean-service/\nhttps://desertfirstcleaning.com/house-cleaning-services/\n\nPlease don’t hesitate to contact us if you have questions. Thank you and Have a good one!",
        "I got called into work. Plz confirm she is doing the baseboards ",
        "Thank you 😊",
        "Thank you! please update us today 😊",
        "Hi Derek, Good morning! We wanted to check in and see if you still need a cleaning service. Our professional experienced crew is ready to clean your home and provide a satisfying result.\n\nIf you are still interested, please check the link below of your booking summary to check the pricing.\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/e10173b7563e181244da5074a56936bd\n\nHere’s more information about the clean we quoted you:\nhttps://desertfirstcleaning.com/deep-clean-service/\n\nPlease don’t hesitate to contact us if you have any questions. Have a great day!",
        "Hey Cindy, it's a deep clean job, and that is the status of their bathroom.",
        "I'm getting it cleaned up now ",
        "I need her to know the key is under the may",
        "Great. Thanks",
        "Hi Alia, Cindy updated us that she is done, I just want to check on you. How was the cleaning you Cindy?",
        "Good morning Tashayanna! I'ts Jen, I just want to know if you met Sheila and she did walk you through before you clean?",
        "No problem! ☺️",
        "Hi Cindy, here are the details for Saturdays job!\n\nJob for SATURDAY:\nETA 7:30-8:30 AM\n431 S Marina St\nPrescott, AZ, 86303\n2bd | 1ba | 1001 - 1500 sq/ft\nMove-in cleaning\nhttps://desertfirstcleaning.com/move-in-move-out-cleaning-service/\nPay $169.12\n\n- Possible for additional carpet cleaning\n__________________________\n\nETA 1-2 pm\n4549 N Tonto Way,\nPrescott Valley, AZ, 86314\n3bd | 2ba | 1001 - 1500 sq/ft\nMove-in cleaning - https://desertfirstcleaning.com/move-in-move-out-cleaning-service/\nPay $189.75\n\nCustomer note: bring a ladder",
        "She'll be your regular customer for a biweekly clean every Thursday 😊\nPlease invoice us\n$81.81 -  #20230217-52215",
        "just waiting on laundry to get done",
        "Hey Pamela! This is John, the owner at desert first cleaning. You're messaging us off business hours, so Jen isn't actively monitoring the phones. I checked the schedule for Monday, and you are booked at 1 pm",
        "Heres the address Kayla, but I'm waiting for Johns response. I'll get back to you if its all good to go.\n4818 E Cielo Grande Ave, Phoenix, AZ 85054, United States",
        "Hey Kayla, update us when you are on your way to Janice. Thank you!",
        "Hey Kayla, unfortunately, I haven't received a response from John. If ever, tomorrow are you available? I'll assign this job to you once I get an answer from John.",
        "van u send invoice number and total",
        "Am I still a customer?",
        "rtxyrs agailable tomarrow\n",
        "No worries, Kayla is our best cleaner, especially for Airbnb/Vrbo properties 😊",
        "Hi Cindy, about your Job for tomorrow, I sent you the incorrect amount. Please see the details below. Thank you!\n\nETA 9-10 am\n1230 Northwood Loop\nPrescott, AZ, 86303\n3bd | 3ba | 4001 - 4500 sq/ft\n2 extra room\nMove in clean\nhttps://desertfirstcleaning.com/move-in-move-out-cleaning-service/\nPay 395.06\n\n- If you have assistance to help you, that would be great!",
        "Hello, this is Desert First Cleaning. Sorry we missed your call. We are on the phone with another customer, and will call you back momentarily.\n\nIn the meantime, could you please send us the following information:\n* The type of clean you want\n* The number of bedrooms in your home\n* The number of bathrooms in your home\n* The square footage of your home\n\nIf you're not sure of the kind of clean you want, check out our cleaning checklists, which detail our services:\nhttps://desertfirstcleaning.com/cleaning-checklist/\nhttps://desertfirstcleaning.com/deep-clean-checklist/\n\nIf you'd like to book online, you can do so here:\nhttps://desertfirstcleaning.com/book-now/",
        "Biweekly Job for your regular customer today!\n\nETA 11am-12nn\n2bd | 3ba | 2001 - 2500\n15426 N BOWLING GREEN DR\nSun City, AZ, 85351\nStandard clean\n138.36",
        "Hi Kim, Cindy is already on the property, and she met your brother-in-law. Thank you!",
        "Did you do a walkthrough with Janice?",
        "That is fine. Thank you",
        "Perfect! thank you",
        "Are you done for Bobby Delocas?",
        "Good morning Kayla! here are the details for your Job today\n\nETA 10-11am\n4bd | 3ba | 2501 - 3000 sq/ft\n4818 E Cielo Grande Ave,\nPhoenix, AZ, 85054\nMove in clean\nPay $302.13",
        "door code? ",
        "tenants did not want me tsking pics cause movers were moving in furniture while iwa i told the management lady toos vcleaning",
        "#20230331-50882 - $93.48",
        "Good afternoon, please see pictures from the current guest. The housekeeper did not clean the home how it should be. When you have time give me a call.",
        "all is good customers are very happy",
        "more like 3000",
        "I'll call him later. ",
        "Good morning Kayla! please invoice us. \nPay $302.13 - #20230331-39995",
        "Np! It's in my calendar! ☺️",
        "This is my address to avoid this in the future. \n2121 w Main St\nMesa AZ, 85201",
        "Hi Kylee, Pamela is asking your ETA.",
        "I just called her and she said she will be there before 2pm",
        "Please update me, if she wants to cancel",
        "I'm going to cancel your appointment for today Pamela with cancellation charge of $75. See you on Friday same time 1-2pm ETA.",
        "Awesome! Thank you, Cindy!",
        "No worries I'll ask her to take an after picture 😊",
        "I rolled them up so she can vacuum and mop. Then she can unroll and vacuum ",
        "Thank you Michelle, please message us again if you need a cleaning service in the future. Have great one!",
        "Garage code is \n1982 Enter",
        "I m here cleaning now ",
        "Good Morning Cindy! Please update us on your ETA for your 1st job. Thank you!",
        "on my way to job now",
        "talked to managment ",
        "Will I still get service Monday and Friday 1-2?",
        "First set of photos are before second set of photos are after",
        "Have you met the owner?",
        "Yeah about 2800sqft",
        "Hi Troy, it's Jen. Sorry for the late response. The last time we visited the property was on the 27th, and I  believe Kayla called you for a walkthrough.",
        "o even jave pics",
        "Hey. Jen I have completed both cleaning jobs for Steve in Prescott and Evelyn in Prescott Valley I just need the reference number so I can request payment. Thank you have a great day ",
        "Good morning Kylee! you have an appointment with Pamela today 1-2pm ETA.",
        "Perfect! Thank you!",
        "Kylee will call you",
        "Tashayanna, please take after pics, especially on the baseboards. Thank you!",
        "Is that the rugs?",
        "Great! thank you, please invoice\nPay - $127.39 #20230328-97333",
        "Ok thank you ",
        "OK we're ready anytime you are. It shouldn't take over 2 hours. The address is 7557 N Dreamy Draw# 223, Phx, 85020. ",
        "Not really. Overall it's in pretty good shape and we've done a lot of the cleaning already. The kitchen and appliances just need a bit of a spiff. The bathroom needs a good cleaning, as well as the windows. We would like the two ceiling fans to be dusted the two or three intake outlet, air vents cleaned, and the floors mopped. We just repainted so the walls and baseboards are fine. Both the built-in oven and microwave are clean the inside of the refrigerator should be wiped down but it's not bad.",
        "No worries, I received your confirmation here. I'll update you tomorrow when Cindy is on her way. Thank you so much Derek for booking with us! Have a nice day!",
        "Just the bedroom ?",
        "Hi Michelle, Kayla just finish the cleaning and she is waiting now for your husband so they can do a walk through. 😊",
        "Sounds good! thank you Kayla! Whats your availability for tomorrow and Saturday? So I can accept a job for you if ever.",
        "Hey Kylee, please don't forget your schedule with Pamela Whittington tomorrow. Thank you!",
        "Good morning Kylee!",
        "did u clise the deal on sat",
        "Hey Kayla please update when you are there.",
        "Is everything ok?",
        "yes we talked",
        "Hi Pamela, let me call Kylee, but I sent her a msg. earlier to remind her and that is between 1-2pm",
        "Copy on that 😉 Thank you!",
        "You're welcome ! 🙂🙃",
        "No thank you",
        "I think she found a cheaper",
        "Thank you so much!",
        "Let me call her",
        "No problem ",
        "Plz no pet deodorizer ",
        "They did a very good job. ",
        "waitingon him to get here to do walk thru",
        "Do you have the before and after picture?",
        "Cindy will be there in 20min. 😊",
        "Perfect! thank you!",
        "Hi Derek, usualy she arrived between 1-2pm! I'll update you if she can send me a message like 15min. before she arrive.",
        "Hello, this is Desert First Cleaning. Sorry we missed your call. We are on the phone with another customer, and will call you back momentarily.\n\nIn the meantime, could you please send us the following information:\n* The type of clean you want\n* The number of bedrooms in your home\n* The number of bathrooms in your home\n* The square footage of your home\n\nIf you're not sure of the kind of clean you want, check out our cleaning checklists, which detail our services:\nhttps://desertfirstcleaning.com/cleaning-checklist/\nhttps://desertfirstcleaning.com/deep-clean-checklist/\n\nIf you'd like to book online, you can do so here:\nhttps://desertfirstcleaning.com/book-now/",
        "Hi Mccaine, thanks for your call. Please accept the booking from the link below for us to put you on our calendar. Please take note that we provided all supplies and equipment and our professional, experienced crew is ready to clean your home and provide a satisfying result. Thank you!\n\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/0a90895ce5c9ba52e66a5ae4585fa7ec\n\nHere’s more information about the clean we quoted you:\nhhttps://desertfirstcleaning.com/house-cleaning-services/\n\nTerms of service:\nhttps://desertfirstcleaning.com/terms-of-service/\n\nFeel free to send us a message if you have any questions. Thank you and Have a great day!",
        "Just arrived",
        "Good morning Pamela! Kylee will be there between 1-2pm today. Thank you!",
        "Kayla is now on her way. Is there any special instruction on how to get in?",
        "Gate on West Side is always open for construction workers.",
        "One moment for the time",
        "Gate on West Side is always open for construction workers. \n",
        "need gate code to neighborhood",
        "I doubled check that in Zillow yesterday. It has 2835 sqft. About Troy, the Airbnb, did you call him last time you cleaned the property? Because he is complaining today. ",
        "For the fridge, that is not included in the standard cleaning. Only the exterior, All interior of appliances and cabinets need a deep clean or add-on. ",
        "Finished tanto way",
        "Good morning Cindy! sorry for the late response. please invoice us!\n\nPay $169.12 - #20230327-47511 \nPay $189.75 #20230330-45398",
        "koolalready comfirmed with ger",
        "Hey Kylee, please let me know when you are on your way to Pamela Whittington. Thank you!",
        "Also that's an hour away. I prefer not to travel more than 45min for gas consumption purposes.",
        "Kylee said she wouldn't be here today that another girl was coming",
        "I know about the charges thanks",
        "Thank you ! I appreciate the text . 🙂",
        "Thank you  Monday and Tomorrow are perfect. What was. Sign in for? ",
        "You have a schedule with Pamela tomorrow. Please let me know if you have any  concern cos I missed a call from you earlier.",
        "Thank you!!",
        "The gate code is 23545, continue straight and go around the water fountain and turn to the right. There is a lot of guest parking available it is building 4.",
        "What time do you think you can be there? cos her husband was there today.",
        "It's ok, Kylee. Important now you are ok.",
        "Hey Kylee, please confirm your appointment today with Pamela, please. Thank you!",
        "I  will be there in  20 minutes ",
        "I'm sorry about the last minute call. I was in severe pain and had to do in for emergency surgery",
        "Would that also include dusting? ",
        "$233 a month? Or per cleaning? ",
        "Hey Kayla, can you do another cleaning after that? 4 bed/3 bath/2835sqft Move in clean.",
        "No thank you! I appreciate it though!",
        "Can you send me invoice # for Bobby please and I am all set at Pam's ",
        "No not today. I'm booked this entire week outside of our one appointment actually.",
        "Hey Kayla, sorry late response. ",
        "that was a big frikon house",
        "Yes, just want to remind you 😄",
        "Excellent. She is so kind! My house looks great!",
        "Hi Janice, just want to check on you how was the cleaning of Kayla today?",
        "Liked “All good for Suzanna 😊”",
        "Good morning Cindy! please let me know your ETA to your cleaning today. Thank you!",
        "I'm here, the customer is not answering the door",
        "Hi Suzanna, Good afternoon! Tashayanna messaged us that the meeting she was supposed to attend today was rescheduled for tomorrow morning. But she can still do the cleaning but her ETA will be 11:30am instead of 9am. Hope you understand. Thank you!",
        "I just charged the customers yesterday because I'm off during weekend. But, I'll make sure to follow up on that with Josh. Sorry about that.",
        "Thanks ! I'll have to check with my brother in law with that .",
        "Even the 17th would work",
        "No problem, Thank you for letting us know, Nancy. Feel free to contact us if you need our services in the future. We are always happy to help. 😊",
        "Please let me know when you are there and if you could please take some before and after pics. Thank you!",
        "Hi Michelle, Good morning! Is this still for a move out clean?",
        "I have a customer here and I will assign him to you for Tuesday Next week. I'll send you the details in a sec.",
        "Good morning Kylee! your schedule today with Pamela is at 1-2pm ETA. Thank you!",
        "https://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/49854e8924cb35feab628fc03c764f18",
        "Sounds good thank you!",
        "Hope you are ok Kylee 😥",
        "Hey Bobby, I have Kayla for you, what time do you need us?",
        "been sitting here for an hr  jow do i get in the house",
        "I spoke with the management they said it should be no code",
        "It's only 10:30. ",
        "She's not working today ",
        "I needed service done before 4pm so I'll have to cancel service today",
        "Great. Thanks!",
        "Awesome! thank you!",
        "Good morning Suzanna! Update from Tashayanna. She is 10min away because of a bit of traffic.",
        "Good afternoon. Unfortunately I had to reschedule a very important meeting to tomorrow morning. I can still make the appointment, but my arrival time will have to be 11:30 instead of the original time. My apologies.",
        "Do you know when I will be getting payment for Saturday ",
        "We're glad to know that you are satisfied with the outcome. Feel free to contact us again if you need a cleaning service in the future. And I hope you have some time today, and we would appreciate it if you could give us a review.\n\nWe are a small business, and much of our success depends on online reviews. If you could leave us a 5-star review on Google, it would really help us.\nhttps://g.page/r/CfI7zpAl6UkbEB0/review",
        "https://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/acca3a226de0108fb30963e73031025e",
        "Fabulous that's such good news. W when she gets to the complex, she will need to enter a code to get the gate open. That code is 23545 have her continue straight and go around the water fountain and turn to the right. There is a lot of guest parking available it is building 4. My husband will be there if she gets lost or needs anything she can text him at 831-588-3975. Thanks, Jen.",
        "Good morning Kylee!",
        "Sure, let me change it, one moment.",
        "I have a afternoon job on Tuesday so can you schedule it for in the morning if possible ",
        "No she didn't book to us",
        "Let me check with the customer, cos we moved it already.",
        "Perfect! have you met Kim's brother-in-law?",
        "Thank you for the update!",
        "Let me follow up Josh on that.",
        "ok, one moment",
        "https://docs.google.com/document/d/1nAEAX88ENbdalZ01QubZ1bDY9KYRwMByddFOeDEBCW8/edit?usp=sharing",
        "I'll pass that to her 😊 Thank you!",
        "Hey Suzanna, Tashayanna is done, and she put the key back under the mat. Here's the link for the photos. Thank you so much!\n https://photos.app.goo.gl/AmH25z1J1Rm7W8Wa9",
        "Thank you! Please invoice us \nPay 395.06 - #20230314-76984",
        "I put the key back under the mat",
        "Cindy here is your MAIDILY logins\nUserName: swaybus\nEmail: swaybus10108@gmail.com\nPW: Cindy2023",
        "My husband is there now. What time today could they get there?",
        "I have available crew today her name is Kayla and she will be there before 11am 😊",
        "I'm trying to pay and book. Completed filling out the credit card info but it won't let me press the accept button. It says card is verified",
        "Kayla called him, and he told Kayla to close the door. Maybe he leave.",
        "booked friday, booked from 12-2 on saturday",
        "Thank you! They will be our regular customers if they like us! Please empress them. 😁",
        "Hi Pamela, Kyee called me a while ago. Unfortunately, she can't do it today because of an emergency. But I'll try to contact my other cleaner to do the cleaning.",
        "Ok just finished ",
        "The address go from 3088 to 3091",
        "We are glad to know that you are satisfied.❤ Would you like me to schedule you for a bi-weekly cleaning?",
        "I don't have the customer's  phone number so I will wait here for a bit hopefully you get this  message ",
        "Hi Cindy, just want to send a reminder for your job tomorrow April 10. Thank you!\n\nETA: 9-10am\n850 S Hwy 69 Unit 16\nDewey, AZ, 86327\nSingle wide Mobile home with 3 bed 2 bath about 1000sqft\nMove in Clean\nPay $175.35",
        "Hello Suzanne, want to check on you. How was the cleaning of Cindy? 😊 ",
        "Hello how much do you charge to clean biweekly? 1500sq ft house. Basic cleaning. 2.5 bathroom and sweep and mop all common areas and entry way ",
        "Yes how much do you charge hourly?",
        "Ok, best of luck with them.",
        "Ok thank you I'm getting multiple quotes. Another company charging me $119 but thank you",
        "If it doesn't work, let us know.",
        "Here's the link for your booking summary. Feel free to accept the booking for us to put you on our calendar. Thank you!\n\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/0bf0d6b3cb501d7b34789886f10ff73a\n\nHere’s more information about the clean we quoted you:\nhttps://desertfirstcleaning.com/move-in-move-out-cleaning-service/",
        "Hi there, this is Jen with Desert First Cleaning. We wanted to check in and see if you still need a cleaning service. Our professional experienced crew is ready to clean your home and provide a satisfying result.\n\nIf you are still interested, please check the link below of your booking summary to check the pricing.\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/0bf0d6b3cb501d7b34789886f10ff73a\n\nPlease don’t hesitate to contact us if you have any questions. Have a great day!",
        "I. Understand I'm not trying to be difficult ",
        "Thank you that's very kind much appreciated.",
        "All done.\nhttps://photos.app.goo.gl/AmH25z1J1Rm7W8Wa9",
        "Liked “We're glad to know that you are satisfied with the outcome. Feel free to contact us again if you need a cleaning service in the future. And I hope you have some time today, and we would appreciate it if you could give us a review.\n\nWe are a small business, and much of our success depends on online reviews. If you could leave us a 5-star review on Google, it would really help us.\nhttps://g.page/r/CfI7zpAl6UkbEB0/review”",
        "My brother in law said they were very thorough and professional .",
        "Hey Cindy, I booked you for Monday April 10, for a move-in clean.\n\nETA: 9-10am\n850 S Hwy 69 Unit 16\nDewey, AZ, 86327\nSingle wide Mobile home with 3 bed 2 bath about 1000sqft\nPay $175.35",
        "You have my email right.",
        "Hey Kayla, are you available today for an hourly job?",
        "Sounds good! Thank you so much, Michelle!",
        "Sorry think I will do it myself thank you for you time and info",
        "Sounds good! try to call him 831-588-3975",
        "Hi Keri, Good morning! Thank you for the early notice. I'm moving your schedule to the 17th now.",
        "Please invoice us $80 - #20230306-51165",
        "How was her cleaning?😊",
        "Saturday Job April 08\n\nETA 9-10am\n2bd | 2ba | 500 - 1000 sq/ft\n3090 Montana Dr, Unit 5 H\nPrescott, AZ, 86301\nDeep Cleaning - https://desertfirstcleaning.com/deep-clean-service/\nPay $194.77\n\n(No need to clean the wall and baseboards, We changed it to clean the Interior and Exterior Refrigerator and the Interior and Exterior Cabinet Wipedown )",
        "I have Kayla for you and she will be there between 12:30-1pm. Thank you!",
        ",=.all done client wad very happy",
        "Hi Cindy, Just want to check on you if you are done?",
        "Thanks. Hey if Cindy can give us a little bit of a better idea of arrival time at any point it would be appreciated. But no big deal",
        "Thank you! please invoice Pay $111.71 #20230316-65025",
        "Everything good. Cindy was great. Thank you",
        "Thank you, Cindy! Please invoice 20230406-42357\n- 194.77\n",
        "Thank you  your awesome ",
        "There is no 3090 ",
        "Good evening! I'd be happy to help you with that. How many bedrooms are in the home?",
        "Ok, here's what we'd normally do on a standard cleaning:\n\nhttps://desertfirstcleaning.com/house-cleaning-services/\n\nHowever, it sounds like you don't want all of that done. If you just want floors done, I recommend we just quote you hourly. Does that sound good to you?",
        "I also need bathrooms cleaned and kitchen counters tops. ",
        "Hey Suzanna, Tashayanna asks if you want her to unroll the works or leave them as they were when she walked in your residence.",
        "I was just hoping to get lunch when I'm done but if it's a problem I can just go home and find something ",
        "Hi Kim, Cindy is done with the cleaning and just want to check on you. How was the cleaning of Cindy?",
        "Hoping you will received it today. 🤞",
        "Hi! Hey I've got company and would like to move my cleaning to after they leave. Could we do it the week of the 17th?",
        "Let me call my crew.",
        "Kayla, please update me when you are done, cos we quoted her for 2 hours only. Thank you!",
        "The address is 7557 N Dreamy Draw# 223, Phx, 85020.\n\nOverall it's in pretty good shape and they've done a lot of the cleaning already. The kitchen and appliances just need a bit of a spiff. The bathroom needs a good cleaning, as well as the windows. they would like the two ceiling fans to be dusted the two or three intake outlets, the air vents cleaned, and the floors mopped. they just repainted so the walls and baseboards are fine. Both the built-in oven and microwave are clean the inside of the refrigerator should be wiped down but it's not bad.",
        "whats invoice number",
        "Thank you. You too. ",
        "Could you please resend me the payment receipt changing the address to reflect the Dreamy Draw address? That way there won't be issues if we should be audited. Thx again ",
        "Did he leave?",
        "Hi Cindy, Please update us when you are on your way and please take before and after pictures. Thanks!\n\nETA: 1-2pm\n2bd | 2ba | 1501 - 2000 sq/ft\n1235 Lago Vis,\nPrescott, AZ, 86301\nDeep Clean - https://desertfirstcleaning.com/deep-clean-service/\nPay - $213.15\n\n- need to focus on the bathroom",
        "Correct address:\n3090 Montana Ct UNIT 5H, Prescott, AZ 86301",
        "Great very happy but I favor Kylee but seriously they are both the best worker bees I ever was lucky enough to clean my house I'm very pleased with their service.\nSincerely,\nPamela and Patricia Kaatz and Whittington ",
        "Hi Derek, It's Jen with Desert First Cleaning. Here's the link for your booking summary. Feel free to accept the booking for us to put you on our calendar. Thank you!\n\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/e10173b7563e181244da5074a56936bd\n\nHere's more information about the clean we quoted you:\nhttps://desertfirstcleaning.com/deep-clean-service/\n\nFeel free to send us a message if you have any questions. Thank you and Have a great day!",
        "Hi Derek, It's Jen with Desert First Cleaning. Here's the link for your booking summary. Feel free to accept the booking for us to put you on our calendar. Thank you!\n\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/e10173b7563e181244da5074a56936bd\n\nHere's more information about the clean we quoted you:\nhttps://desertfirstcleaning.com/deep-clean-service/\n\nFeel free to send us a message if you have any questions. Thank you and Have a great day!",
        "Hey Cindy, Good morning! Keri Pool moves her schedule to the 17th . And here are your logins to MAIDILY logins\nUsername: swaybus\nEmail: swaybus10108@gmail.com\nPW: Cindy2023",
        "Great! I will update the previous invoice that I created to an hourly job. Would you like us to come today or tomorrow?",
        "Job for tomorrow, 04/07\n\nETA: 1-2pm\n2bd | 2ba | 1501 - 2000 sq/ft\n1235 Lago Vis,\nPrescott, AZ, 86301\nDeep Clean - https://desertfirstcleaning.com/deep-clean-service/\nPay - $213.15\n\n- need to focus on the bathroom",
        "we did wslk thru hes happy",
        "Hey Michelle, could you please check if its work, we updated the address and resent the receipt.",
        "uhhh.. Thank you so much, we are so very happy to know that. No worries once Kylee is ready to work on Monday I'll book you for her. 😉",
        "Hi Derek, just want to check on you. How was the cleaning, Cindy 😊",
        "She's right there. She was looking for Montana drive. You should see her momentarily ",
        "Hi Kim, thanks for your call. Please accept the booking from the link below for us to put you on our calendar.\n\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/53ef49631ff2294fb33d65aa8cc927e9\n\nHere’s more information about the clean we quoted you:\nhttps://desertfirstcleaning.com/move-in-move-out-cleaning-service/\n\nTerms of service:\nhttps://desertfirstcleaning.com/terms-of-service/\n\nFeel free to send us a message if you have any questions. Thank you and Have a great day!",
        "April 11, 2023\nETA 9-10am\n3bd | 2ba | 2001 - 2500 sq/ft \n409 N French Dr, Prescott,\nPrescott, AZ, 86303  -  Lot box code 1733\nMove in Cleaning \nEXTRA:\nInterior Windows & Blinds x 15\nExtra Room x 1\nPay $302.66\n\n- Please double check the number of windows and blinds so we can adjust it if its lessthan 15 because the customer is not sure on it.",
        "Great! have you met Pamela?",
        "I'll be able to do Pam's cleaning on Monday",
        "Hello, this is Desert First Cleaning. Sorry we missed your call. We are on the phone with another customer, and will call you back momentarily.\n\nIn the meantime, could you please send us the following information:\n* The type of clean you want\n* The number of bedrooms in your home\n* The number of bathrooms in your home\n* The square footage of your home\n\nIf you're not sure of the kind of clean you want, check out our cleaning checklists, which detail our services:\nhttps://desertfirstcleaning.com/cleaning-checklist/\nhttps://desertfirstcleaning.com/deep-clean-checklist/\n\nIf you'd like to book online, you can do so here:\nhttps://desertfirstcleaning.com/book-now/",
        "It was great!  Thanks so much 😊.",
        "i dont know i gota go get a tire ",
        "btw, Cindy can you do a carpet cleaning? cos that customer for Saturday possible he will be adding a carpet cleaning, but he needs to measure his carpet first.",
        "Good morning, can my cash app request please be paid. I need to pay my rent today.",
        "Hi Stephany, It's Jen with Desert First Cleaning. Feel free to accept the booking using the link below for us to put you on our calendar. Thank you!\nhttps://maidily.com/iframes/customer-portal/c18912bc443f461cc8d17f0796fa99c5/75e6bc4352b99367d0f949b978c0ce12\n\nFor a Deep cleaning - $664\n\nHere’s more information about the clean we quoted you:\nDeep Clean - https://desertfirstcleaning.com/deep-clean-service/\nStandard Clean - https://desertfirstcleaning.com/house-cleaning-services/\n\nFeel free to send us a message if you have any questions. Thank you and Have a great day!",
        "Like a charm thx!",
        "Good morning! I'll follow up on that to Josh. But please keep in mind our new SOP.\nThe SOP states: We pay cleaners 55% of the full price of a job. Payouts are completed in the mornings, approximately every other day, using Cash App. Given the time it takes to confirm a clean is satisfactory and initiate a charge to a customer, cleaners should expect a wait of 48-72 hours for Cash App payments to be paid. Additionally, if the job number is missing or inaccurate on a Cash App request, it will delay the payout by a minimum of 24 hours",
        "ETA 11:30am (11am is the check out time and next customer will check in at 4pm)\n16606 S 38th Way Phoenix, AZ\n3bd | 3ba | 1501 - 2000 sq/ft\nEXTRA 3 loads of Laundry - (face towels, body towels, and the sheets for all the beds and pillowcases)\nAirbnb clean\nAmount $150.26\n\n\n- Laundry detergent is in the cabinet in the garage\n- there should be 2 face towels and body towels in every room\n- wash the towels in the bedroom downstairs, and they should be in the cabinet\n- check the detergent and dishwasher tablets\n- house has a wood floor please do not use water, use wood floor cleaner find BONA in the laundry room\n- Please also check if there are some toilet tissue\n\n-  After cleaning do a video call with the customer because he is in the other state. he is our Airbnb customer.",
        "Do you have a cleaner for today at the same location? They check out in about and hour and half. ",
        "What time do you think your ETA? cos this job is for 1-2pm ETA\n\n2bd | 2ba | 500 - 1000 sq/ft\n9033 E Gary Ln Mesa, AZ, 85027\nStandard clean \nPay $111.71\n\nclean the exterior of cabinets clean the 1 bath room from the room that no need to be clean",
        "i can be there at 1230",
        "Thanks!  She's here.",
        "Found it thank you ",
        "Hi to join our (β.t.C) discussion Groups , where you can learn to earn 700-1000 Every day, Please click whatsapp://chat/?code=LyRSQLKicmZAzm8JCtFrb2 SandraNWe",
        "no good  that one is pain to deal with amd i dont likr her supplies",
        "Hey Andrea! I just want send you a reminder for your biweekly clean tomorrow. Thank you! \n\nMonday, April 10\n\nTom and Sherry Baran\n1862 South Skyview Place\nTucson, AZ, 85748\n(520) 271-4380\n\nETA 10AM\n3bd | 2ba | 1001 - 1500 sq/ft\nStandard clean\n$154.82",
        "You're welcome ",
        "Hello, this is Desert First Cleaning. Sorry we missed your call. We are on the phone with another customer, and will call you back momentarily.\n\nIn the meantime, could you please send us the following information:\n* The type of clean you want\n* The number of bedrooms in your home\n* The number of bathrooms in your home\n* The square footage of your home\n\nIf you're not sure of the kind of clean you want, check out our cleaning checklists, which detail our services:\nhttps://desertfirstcleaning.com/cleaning-checklist/\nhttps://desertfirstcleaning.com/deep-clean-checklist/\n\nIf you'd like to book online, you can do so here:\nhttps://desertfirstcleaning.com/book-now/",
        "That's fantastic news. We are so happy you're satisfied with her work.",
        "I will give you guys a ring sometime soon. My wife and I still need to figure out our schedules. Talk to you soon",
        "I'll be there",
        "Hi Pamela, I spoke with my boss John, and we will not charge you this time for the cancelation, but please, next time, notify us before the day of your appointment. Thank you!",
        "We charge $75/hr. However, since you'd be booking biweekly, I'll give you 15% off. I estimate it will take 2-3 hours to complete the floors, bathrooms, and countertops.\n\nIf you'd like to book with us, we'll send someone out and bill you for the hours worked. It will come to 127.5 to 191.25.\n\nWhen were you thinking about having us start.",
        "Per cleaning",
        "Ok thank you",
        "We'll be happy to do your dusting. At the end of the day, we'll just bill you for the hours worked.\n\nWe can do the full standard clean for $233.32. This is what most of our customers do, and they are very happy with the result:\n\nhttps://desertfirstcleaning.com/house-cleaning-services/",
        "ETA 11:30am (11am is the check out time and next customer will check in at 4pm)\n16606 S 38th Way Phoenix, AZ\n3bd | 3ba | 1501 - 2000 sq/ft\nEXTRA 3 loads of Laundry - (face towels, body towels, and the sheets for all the beds and pillowcases)\nAirbnb clean\nAmount $150.26\n\n\n- Laundry detergent is in the cabinet in the garage\n- there should be 2 face towels and body towels in every room\n- wash the towels in the bedroom downstairs, and they should be in the cabinet\n- check the detergent and dishwasher tablets\n- house has a wood floor please do not use water, use wood floor cleaner find BONA in the laundry room\n- Please also check if there are some toilet tissue\n\n- After cleaning do a video call with the customer because he is in the other state. he is our Airbnb customer.",
    ]
